# Generated by Django 3.1.5 on 2021-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, verbose_name='币对')),
                ('last_qty', models.CharField(max_length=32, verbose_name='最新成交的数量')),
                ('last', models.CharField(max_length=32, verbose_name='最新成交价')),
                ('best_ask', models.CharField(max_length=32, verbose_name='卖一价')),
                ('best_ask_size', models.CharField(max_length=32, verbose_name='卖一价对应的量')),
                ('best_bid', models.CharField(max_length=32, verbose_name='买一价')),
                ('best_bid_size', models.CharField(max_length=32, verbose_name='买一价对应的数量')),
                ('open_utc0', models.CharField(max_length=32, verbose_name='UTC+0时开盘价')),
                ('open_utc8', models.CharField(max_length=32, verbose_name='UTC+8时开盘价')),
                ('timestamp', models.DateTimeField(verbose_name='时间')),
            ],
        ),
    ]
